### ISSUE TITLE
Suggestion: announce each file at the top of the loop

### ISSUE THREAD

**Issue by kcharter** [kimlew/bash-sort-images#3]
Looking at the first few lines of the loop:

https://github.com/kimlew/bash-sort-images/blob/16847406d5bedc500235cf93c761493c8a512b7d/sort_images.sh#L52-L61

the first `echo` statements are for the two dates you try to extract with `identify`. I suggest you add another `echo` statement at the top of the loop announcing that you are examining a new file. Something like

```
echo "looking at file: ${a_file_name}"
```

**Comment by kimlew** [comment]
@kcharter Good suggestion. Done.

**Comment by kcharter** [comment]
@kimlew looks fixed in commit 064a07ea4bde4913d8b5c225f45c317a48b852cf. Let me know if you'd prefer that I close the issue.
